- file: dest={{install_dir}}/hadoop/etc/namenode state=directory
- template: src=hdfs-site.xml dest={{install_dir}}/hadoop/etc/namenode/hdfs-site.xml
- template: src=core-site.xml dest={{install_dir}}/hadoop/etc/namenode/core-site.xml
- template: src=supervisor.conf dest=/etc/supervisor/conf.d/zkfc.conf
- supervisorctl: name=zkfc state=present
- supervisorctl: name=zkfc state=restarted
- supervisorctl: name=namenode state=restarted

